[versions]

asm = "9.5"
cafedude = "1.10.2"
lljzip = "1.3.1"
picocli = "4.7.4"
jsr305 = "3.0.2"
slf4j = "2.0.7"
logback-classic = "1.3.7"
jansi = "1.17"
junit-jupiter = "5.9.2"

checker-processor = "1.2.7"
shadow = "8.1.1"

[plugins]
checker-processor = { id = "gov.tak.gradle.plugins.checker-processor", version.ref = "checker-processor" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[libraries]
# ASM
## All purpose Java bytecode manipulation and analysis framework
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm-tree = { group = "org.ow2.asm", name = "asm-tree", version.ref = "asm" }


cafedude = { group = "com.github.Col-E", name = "CAFED00D", version.ref = "cafedude" }
lljzip = { group = "software.coley", name = "lljzip", version.ref = "lljzip" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }

# SLF4K
## SLF4K is a set of kotlin extensions for SLF4J
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
# Logback
## The reliable, generic, fast and flexible logging framework for Java
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }

# JUnit
## Unit testing framework for Java
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }

[bundles]

asm = [
    "asm",
    "asm-tree",
]

junit = [
    "junit-jupiter-api",
    "junit-jupiter-engine",
    "junit-jupiter-params",
]
